### ISSUE TITLE
listus: Adding a new item to a list adds 3 items in UI

### ISSUE THREAD

**Issue by trakhimenok** [sneat-co/sneat-apps#1520]
The server side works correctly adding just a single item to DB. But UI shows 3 of the same. If page refreshes it show correct number of items. Also does not reproduce if there is items in the list already.

**Steps to reproduce:**

1. Create a new team or clear all listus module data in DB
2. Refresh app
3. Go to Lists => Groceries
4. Add 1 new item
5. See 3 items added instead of 1 as on screenshot

![image](https://github.com/sneat-co/sneat-apps/assets/533159/5769e0ff-888c-46ae-817f-f2c28d578b61)

1. Find and explain a root cause (if possible)
2. Create a PR linked to this issue and put it in draft state
3. Develop a unit test
4. Make sure the test is failing in PR pipeline
5. Develop a fix - make sure test is passing in PR pipeline
6. Once PR workflow passes submit a PR for review by removing draft state and adding @trakhimenok as a reviewer.

**Comment by CodeNinja-Pro** [comment]
I changed package.json file manually, that would be the reason of build failure.
I will fix it now.
And in in terms of unit test, when I am trying to run the following command, I encounter so many bugs.
`pnpm run nx serve extensions-listus`
