### ISSUE TITLE
Migrate to ESLint v9 - from .eslintrc.json to the new flat config eslint.config.js 

### ISSUE THREAD

**Issue by trakhimenok** [sneat-co/sneat-apps#1952]
https://eslint.org/docs/latest/use/configure/migration-guide
https://eslint.org/blog/2022/08/new-config-system-part-1/
https://eslint.org/blog/2022/08/new-config-system-part-2/

Relevant renovate PR: https://github.com/sneat-co/sneat-apps/pull/1865

.eslintignore not used anymore
eslintrc.json => eslit.config.js
Relevant issue on NX - https://github.com/nrwl/nx/issues/22769

TODO: Needs AC instructions on how to validate new lint rules.

**Comment by xspace-solution** [comment]
I can fix this configuration in 2 hours.
Please send me a message if you want to work with me.
